### list users
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsInN1YiI6ImZiOWJlZWE2LTYxNWUtNDU1Ny1hZDFkLTMzYTkwNmYyYTExMiIsImlhdCI6MTc0ODYyMjY1MCwiZXhwIjoxNzQ4NjI2MjUwfQ.weWoWRrDZu9Zoe-DBk6TZXGQt06j0ASl4nnKQ6_SJVg

### get user
GET http://localhost:8080/users/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer {token}


### create user
POST http://localhost:8080/users/
Authorization: Bearer {token}
Content-Type: application/json

{
    "name": "mateus",
    "email": "teste@example.com",
    "fone": "+5583998888430",
    "password": "mateus"
}

### update user
PATCH http://localhost:8080/users/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer {token}
Content-Type: application/json

{
    "name": "mateus",
    "email": "mateus@example.com",
    "fone": "+5583998888430"
}

### delete user
DELETE http://localhost:8080/users/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer {token}
