### list users
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGV1c0BleGFtcGxlLmNvbSIsInN1YiI6ImY1NjU0MzlhLWRiODEtNGI2Zi1iNjljLWViMTYyYjJmNmNiNCIsImlhdCI6MTc0NzAwMTY1MywiZXhwIjoxNzQ3MDA1MjUzfQ.6VkJmYQ9WT4ARV67Xmr6sa8kNH_97WzXnfE7aG84EIs

### get user
GET http://localhost:3000/user/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlQGV4YW1wbGUuY29tIiwic3ViIjoiZjU2NTQzOWEtZGI4MS00YjZmLWI2OWMtZWIxNjJiMmY2Y2I0IiwiaWF0IjoxNzQ2OTk5Njk2LCJleHAiOjE3NDcwMDMyOTZ9.8fkqoe6ktMVe6ORbh_Gw5rWYbyEiZmIYWzlTCiY6mRk


### create user
POST http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlQGV4YW1wbGUuY29tIiwic3ViIjoiZjU2NTQzOWEtZGI4MS00YjZmLWI2OWMtZWIxNjJiMmY2Y2I0IiwiaWF0IjoxNzQ2OTk5Njk2LCJleHAiOjE3NDcwMDMyOTZ9.8fkqoe6ktMVe6ORbh_Gw5rWYbyEiZmIYWzlTCiY6mRk
Content-Type: application/json

{
    "name": "mateus",
    "email": "teste@example.com",
    "fone": "+5583998888430",
    "password": "mateus"
}

### update user
PATCH http://localhost:3000/user/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlQGV4YW1wbGUuY29tIiwic3ViIjoiZjU2NTQzOWEtZGI4MS00YjZmLWI2OWMtZWIxNjJiMmY2Y2I0IiwiaWF0IjoxNzQ2OTk5Njk2LCJleHAiOjE3NDcwMDMyOTZ9.8fkqoe6ktMVe6ORbh_Gw5rWYbyEiZmIYWzlTCiY6mRk
Content-Type: application/json

{
    "name": "mateus",
    "email": "mateus@example.com",
    "fone": "+5583998888430"
}

### delete user
DELETE http://localhost:3000/user/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlQGV4YW1wbGUuY29tIiwic3ViIjoiZjU2NTQzOWEtZGI4MS00YjZmLWI2OWMtZWIxNjJiMmY2Y2I0IiwiaWF0IjoxNzQ2OTk5Njk2LCJleHAiOjE3NDcwMDMyOTZ9.8fkqoe6ktMVe6ORbh_Gw5rWYbyEiZmIYWzlTCiY6mRk
