### list users
GET http://localhost:3000/user
Authorization: Bearer {token}

### get user
GET http://localhost:3000/user/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer {token}


### create user
POST http://localhost:3000/user/
Authorization: Bearer {token}
Content-Type: application/json

{
    "name": "mateus",
    "email": "teste@example.com",
    "fone": "+5583998888430",
    "password": "mateus"
}

### update user
PATCH http://localhost:3000/user/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer {token}
Content-Type: application/json

{
    "name": "mateus",
    "email": "mateus@example.com",
    "fone": "+5583998888430"
}

### delete user
DELETE http://localhost:3000/user/f565439a-db81-4b6f-b69c-eb162b2f6cb4
Authorization: Bearer {token}
